### ISSUE TITLE
Using native tables (Table header styles off by a few px)

### ISSUE THREAD

**Issue by stephenmathieson** [segmentio/evergreen#105]
At first, I thought this was something on my end, but looking at the [Storybook](https://segmentio.github.io/evergreen/?selectedKind=table&selectedStory=Basic%20example&full=0&down=0&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel), I see the same bug:

![image](https://user-images.githubusercontent.com/571265/34615379-b3f21c32-f202-11e7-99d6-300c1a77ea70.png)

**Comment by stephenmathieson** [comment]
Maybe we're not accounting for the scrollbar?

**Comment by jeroenransijn** [comment]
Yeah scrollbar is the issue. Not sure if there is a great solution for this.

**Comment by stephenmathieson** [comment]
There must be a solution since only tables drawn by Evergreen have this problem.

Maybe add margin to the header that is the same width as the scroll bars?

**Comment by jeroenransijn** [comment]
Hi @stephenmathieson, to give some clarification around this issue. We are not using native tables in Evergreen, it's a `div` soup instead. As for the scrollbar, keep in mind it's only a issue when you explicitly have scrollbars enabled in Mac OS X, or if you are using Windows. This makes this problem always a little hard to combat.

Some solutions to this are as follows:

## Somehow check in the browser if scrollbars are enabled on runtime and compensate the header with some script.

Pros: best solution.
Cons: Might be hard for people to implement every time. Might be easily overlooked. Potentially buggy.

## Force a stylized scrollbar in webkit (and firefox?) and optionally trigger this with a prop (which has default true)

Pros: No setup required. Nice looking scrollbar.
Cons: Unsure about browser support outside of webkit. Table headers need to know about table body, some dependency here.

Would love to hear any other suggestions, maybe I am missing something obvious here :)

**Comment by Rowno** [comment]
You could try making the table wrapper scrollable instead and position fix the header.

**Comment by stephenmathieson** [comment]
@jeroenransijn would using "actual" table elements (`<table>`, `<thead>`, `<tr>`, etc) make more sense here? Not only would it fix this issue without hacks, but it'd hugely reduce the number of a11y issues.

**Comment by Rowno** [comment]
I Googled about `<table>` a11y and apparently no screen reader actually using the `<table>` markup. 🤷‍♂️

I guess the `<table>` layout days ruined `<table>` a11y forever.

**Comment by stephenmathieson** [comment]
@Rowno SRs certainly do use `<table>` markup. For example, here's how you [navigate tables in VoiceOver](https://www.apple.com/voiceover/info/guide/_1133.html#mchlp2723).

**Comment by jeroenransijn** [comment]
It seems like Facebook's ad platform has tables with no scrolling issue. It be interesting to see their markup.

I am not against supporting real tables. But I know it's going to open another can of worms, which might worse. Thoughts?

**Comment by stephenmathieson** [comment]
What "can of worms" would that be? Native tables work as expected in all browsers and with minimal CSS can "look" the same everywhere too

**Comment by jeroenransijn** [comment]
@stephenmathieson the main issue is probably responsiveness with real tables.  It's been a long time since I actually used `<table>` for layout components because responsiveness has always been a requirement. Which is not a requirement of Evergreen yet — so we don't have to worry about it right now.

Some things that come to mind are `tbody { overflow-y: scroll; }` — and I guess virtualization would work the same as with divs? I guess for as long as we use `table-layout: fixed;` we should be good.

I think I might have been biased by all the anti table propaganda from the aftermath of using tables for layouts. I am more than happy to lean on your skill and knowledge here and try out a POC that uses the native table instead. This will be a breaking change from the current package, so I am not sure how to move forward on this in the short term.

**Comment by stephenmathieson** [comment]
Well I’m +1 for a native solution; IMO the simpler the better for these sorts of things.

Regardless of what a future solution might be, is there plan to fix the orIginal issue (header styles are off)? This seems like a blocker for adopting Evergreen in a customer-facing app :/

**Comment by jeroenransijn** [comment]
@stephenmathieson it is def an annoying issue. Do note that it does not effect Mac users as much, since the default is not to show the scrollbar in place.

I think we should build this for v3. Since it will be a major breaking change.

My priorities right now are documenting what we have and figuring out what we want to change/move into a v3 release.

**Comment by jeroenransijn** [comment]
You can also use position: sticky; and make the parent table scrollable instead of just TableBody:

![table header position sticky](https://user-images.githubusercontent.com/564463/35306142-34421d7c-0051-11e8-90d1-f9c05753d834.gif)
