### ISSUE TITLE
TextInputField bottom margin is inconsistent with FormField

### ISSUE THREAD

**Issue by cdedreuille** [segmentio/evergreen#1054]
I think there's an inconsistency on `TextInputField` compared to `FormField` as it's adding a marginBottom of 24px. In my case, I'm trying to create a form composed of multiple types and I want them to all have a label. As `SelectMenu` doesn't have a label by default I'm using  `FormField` to add it.

My code looks like this:

```
<Space space={16}>
  <TextInputField
    width="100%"
    label="Price Range Min"
    placeholder="Minimum"
  />
  <TextInputField
    width="100%"
    label="Price Range Max"
    placeholder="Maximum"
  />
</Space>
<FormField label="Values">
  <SelectMenu
    isMultiSelect
    title="Values"
    options={newValues}
    selected={listValues}
    onSelect={item => handleOnSelect(listValues, item)}
    onDeselect={item => handleOnDeselect(listValues, item)}
  >
    <Button width="100%">
      {nameValues || 'Select multiple values'}
    </Button>
  </SelectMenu>
</FormField>
```

But I have now inconsistent margins between my inputs as `TextInputField` has by default a 24px marginBottom.

<img width="678" alt="Screenshot 2020-09-22 at 11 40 00" src="https://user-images.githubusercontent.com/1540635/93872860-ab8c9f80-fcc8-11ea-8c86-61c870dea58c.png">

As a work around I'm using `FormField` on `TextInput` instead but it would be great to have some consistency there.

**Comment by Anmol270900** [comment]
Hi! Is this issue still open to work on? May I work on it?

**Comment by cdedreuille** [comment]
@Anmol270900 Still there in V6. Would be great to have it solved. @akleiner2 ?

**Comment by mshwery** [comment]
Hi @cdedreuille – thanks for reporting. I can see how this comes across as an inconsistency though I think it was intentional.

I think the original intent was that TextInputField, TextareaField, SelectField, etc were predefined and somewhat opinionated compositions of the more primitive FormField. They all use FormField under the hood.

It might make sense to bring consistency across the other *Field components and FormField, but I don't think we want to add margin to FormField itself. If we were to make a change here it would probably be to _remove margin_ from the other *Field components so consumers could BYO-margin. 

It's tricky because either change (removing it from *Field components or adding it to FormField) are visually breaking changes.

**Comment by cdedreuille** [comment]
Having both an opinionated and primitive approach is great as it can fit to your need. The main point I'm raising here is the inconsistencies with the other fields. Without changing the existing components you could:
- Add new opinionated components (___Field) to all the other components that compose a form
- Simplify the doc so people can understand both approaches

It's certainly great to have both, just a bit confusing at first to understand why they exist, and why some form elements don't have them.

**Comment by akleiner2** [comment]
Going to backlog this internally - re-visiting form elements (visually, accessibly) is something that we'll look to do in the coming months cc @kamebkj
