### ISSUE TITLE
`isSolid` for Badge is not available at v6

### ISSUE THREAD

**Issue by gencer** [segmentio/evergreen#1096]
This is not working:

```
<Badge color="red" isSolid>...</Badge>
                   ^^^^^^^
```
It seems this props has been removed on `v6`. What is the alternate way of enabling solid color on badges using `v6`? Or, Is it permanently removed?

### Update

Hm.. It seems `v5` documentation shows `isSolid` as an example but props doesn't show either...

**Comment by akleiner2** [comment]
Hey @gencer - that's right, we're removing the prop from the `<Badge />`, but could likely foresee doing this in userland (via a new theming API). 

Since v6 is still under heavy development (hence the pre-release cuts, and not a formal major version release), we haven't done any documentation or broader communication about alternatives or methods forward. For now, I would consider v6 to be "use at your own risk" until we tighten up all the documentation and formalize the API around it. 

That being said, we will make sure to consider adding back an alternative (whether provided by EG, or enable-able in user-land) via a **very** rich theming API, so stay tuned :).

**Comment by akleiner2** [comment]
That being said, `isSolid` is available on Badges and Avatars in v5, but you're right - looks like the `propTypes` don't show it. Happy to accept a PR, if you're willing to add it!

**Comment by akleiner2** [comment]
Going to close this out for now - but let us know if you have nay other questions!
