### ISSUE TITLE
[request] Make demo Storybook available 

### ISSUE THREAD

**Issue by nettofarah** [segmentio/evergreen#11]
It would be cool to link to a running demo of the packages we've implemented so far.
I love sharing what we've been building so far, as it gets people excited about our progress and helps recruit contributors.

I'm happy to take a stab at this if you're too busy, @jeroenransijn

**Comment by jeroenransijn** [comment]
Hi @nettofarah, thanks for creating this issue!

Documentation should definitely be on our Roadmap, and is currently not. I will try to write my thoughts here, that might inspire what will be in the Roadmap:

### Storybook with examples

The first part is to have a Storybook live, which is what you are describing. This will contain simply the component use cases needed for developing, and is lacking as a form of documentation. It won't have code blocks containing usage examples, or property documentation.

This should be fairly straightforward to implement if the packages are actually published (they are no yet at the moment). If that is the case, we can build a static storybook and push that to the `gh-pages` branch. This might require something like Circle for CI, which I am not very familiar with.

### Low scope docs in Storybook

The second part is to create the components that are required to build out documentation. A highlighted `CodeBlock` component, and maybe some useful helper components / utilities in a `evergreen-docs` package. I am thinking `evergreen-docs` will contain some Readme Markdown rendered of some sort.

### Dedicated documentation website

The third part is to create documentation website, similar to how [AtlasKit](https://atlaskit.atlassian.com/) approaches this. This will require a bigger set of components and resources to be available. 

### Design documentation (long term goal)

The last part is to create design documentation. That will be primarily for designers, and is more focused around what is the right way to use a component or patter, instead of showing you how to implement it.

**Comment by jeroenransijn** [comment]
Closing this since the Storybook is now available https://segmentio.github.io/evergreen/

**Comment by harrisrobin** [comment]
@jeroenransijn storybook is working great for the demo, but it would be nice to see the components with their props alongside and be able to play with them right there! I'd be happy to give it a shot.

I don't see it in the roadmap but did you have any plans for this?
