### ISSUE TITLE
React 17 Support

### ISSUE THREAD

**Issue by omonk** [segmentio/evergreen#1152]
Are there any plans to bump the react and react-dom peer dependencies to allow react 17? With the npm version 7 reintroduction of installing peer dependencies it is making it tricky to use evergreen without the `--legacy-peer-deps` flag.

**Comment by mothattack** [comment]
Yeah I was about to start a project with React and Evergreen. Step 1 install react. Step 2 install evergreen Step 3 .......oh...step 2 failed

**Comment by Samuel-Montoya** [comment]
When will this get updated? Such a great package and would love to use it with latest version of React

**Comment by akleiner2** [comment]
Hey y'all -- will look into this before the week's done. My guess is it's as simple as loosening up the peer deps requirement (or getting rid of it altogether) to allow for React 17 (especially since there aren't really any major breaking changes in React 17), but I want to be 100% sure first and test locally. Thanks for the patience here 🤞

**Comment by mothattack** [comment]
Any updates on this?

**Comment by mikemaccana** [comment]
This should hopefully be a small update as you say - as there's no breaking changes between React 16 and 17. next.js users can't upgrade to next 11 until Evergreen supports React 17 so it would be timely if the dependencies were updated.

**Comment by mirnaio** [comment]
Any updates.....?

**Comment by zuhair-naqvi** [comment]
Thumbs up for React 17 please!

**Comment by mshwery** [comment]
Hey folks, quick update – we've made some upgrades internally and with packages that would have led to a breakage on React 17 (this only affects certain components).

Right now it seems the last package that we'll need to fork or switch off of is `react-tiny-virtual-list` due to its reliance on deprecated lifecylece method names.

I started looking into switching to react-window which seems to be the defacto standard these days, but it's noticeably slower than react-tiny-virtual-list (this will affect SelectMenu, Table.VirtualBody, and Autocomplete components).

**Comment by mshwery** [comment]
Ok, gonna cut a release soon now that these have landed:
- https://github.com/segmentio/ui-box/pull/92
- https://github.com/segmentio/evergreen/pull/1281

**Comment by mshwery** [comment]
Released with [v6.3.0](https://github.com/segmentio/evergreen/releases/tag/v6.3.0)!

**Comment by omonk** [comment]
@mshwery - many thanks for your work!
