### ISSUE TITLE
SelectMenu, if "selected" array changes exterally, previosely selected items emit "onDeselect" on click

### ISSUE THREAD

**Issue by psiho** [segmentio/evergreen#1212]
CodeSnbox is here: https://codesandbox.io/s/gifted-dan-tiyhl

Open menu, select all options, then click "reset state to cucomber" button in the title.... visually all seems ok, but now click on Apple. Nothing happens because (check console), event "onDeselect" is emitted even if Apple is not selected.

**Comment by derekvelzy** [comment]
I believe this is because the `setSelectedItemNames` function is never triggered on the reset button click event.

Here's a CodeSandbox where I use a `handleReset` function to trigger both the `setSelectedItems` and `setSelectedItemNames`. I also moved the functions above the return statement for some cleanup.

CodeSandbox: https://codesandbox.io/s/stupefied-sea-sunnk?file=/index.js

**Comment by mshwery** [comment]
This is resolved in latest (v6.2.0).
