### ISSUE TITLE
Toaster hasCloseButton and onRemove do not function

### ISSUE THREAD

**Issue by seth-wat** [segmentio/evergreen#1317]
1) Setting the option `hasCloseButton: false` does not prevent the close button from showing up in the UI
2) The `onRemove` function is not called when the toast is removed from the UI

[examples on codesandbox](https://codesandbox.io/s/busy-haibt-sue8v?file=/src/App.js)

**Comment by mshwery** [comment]
The first issue is probably due to using an `||` instead of `??`:
https://github.com/segmentio/evergreen/blob/29f9c41ff15527dac0892330b8032ccd585b1412/src/toaster/src/ToastManager.js#L74

The other one is because we don't let you pass `onRemove` on individual toasts. That's a prop of the Toast component, but it is not in the settings – the docs may have not been very clear on this.

You can see all the types for the `settings` for `toaster[method](message, settings)` here:
https://github.com/segmentio/evergreen/blob/29f9c41ff15527dac0892330b8032ccd585b1412/index.d.ts#L2612-L2630
