### ISSUE TITLE
Add SVG prop to Avatars

### ISSUE THREAD

**Issue by EstebanBorai** [segmentio/evergreen#132]
Hey I was checking out this repo and I was wondering if it could be possible to have the option of rendering SVG Icons inside avatars or as Icons? This makes possible the availability of any SVG design/code inside a project that is using Evergreen!

**Comment by jeroenransijn** [comment]
Hi @EstebanBorai thanks for checking out Evergreen and taking the time to create an issue — much appreciated! Could you describe your use case or potentially share a simple paper sketch of what you are trying to achieve. As far as I understand it you are asking for support of a `icon` prop on the `Avatar` component — which would render a icon inside of the Avatar instead of the initials or image?

**Comment by EstebanBorai** [comment]
Thanks for your attention @jeroenransijn ! 
Yes! I would like to render SVG Icons inside an Avatar Component just like Material UI does.
It's very useful and let's people use their own designs.

**Comment by Rowno** [comment]
Just FYI, you can already use any image you want using the `src` prop, which can be passed any file path that `<img>` supports (including SVG files). Not sure if that's what you want?

**Comment by EstebanBorai** [comment]
Thanks @Rowno and @jeroenransijn ! I'm setting the issue as closed as the component already supports SVG through `src` prop!
