### ISSUE TITLE
onChange and onBlur event handlers

### ISSUE THREAD

**Issue by ahsan-sabir** [segmentio/evergreen#1509]
I would be nice if we could pass onChange and onBlur event handlers to components such as Combobox and SelectMenu for form libraries like react hook form and formik. There's inputProps present in Combobox but passing onChange and onBlur to it doesn't appear to work.

**Comment by brandongregoryscott** [comment]
Hey @ahsan-sabir,

`onChange` should be available directly on the `Combobox` component, and `onSelect` should serve the same purpose for the `SelectMenu` component. Most of our components are built on top of our `Box` primitive and spread additional props onto the component(s) that are being composed. 

`onBlur` seems to work on the `Combobox` already, but the `SelectMenu` seems to work a little differently, since it relies on the `Popover` component wrapping a trigger component. What would the expected behavior be there?

I'd recommend trying out the interactive code sandboxes on our documentation site! https://evergreen.segment.com/components/combobox

**Comment by ahsan-sabir** [comment]
Hi @brandongregoryscott 

Turns out the lib I was using (react-hook-form) expect onChange to receive event object, which is not the case with Combobox. Moreover passing onChange through inputProps won't work (which works for onBlur)

```
<Combobox
  openOnFocus
  inputProps={{ 
    id: "fruits", 
    name: "fruits", 
    onChange: e => console.log('onChange', e), 
    onBlur: e => console.log('onBlur', e) 
  }}  items={['Banana', 'Orange', 'Apple', 'Mango']}
  placeholder="Fruit"
/>
```

**Comment by brandongregoryscott** [comment]
>onChange to receive event object, which is not the case with Combobox

Correct, most of our component event handlers do not expose the raw event and instead provide a simpler API with the changed item/value only. This makes it easier to work with a regular `useState` hook.

>Moreover passing onChange through inputProps won't work (which works for onBlur)

Yes, you'll want to set the `onChange` property directly on the `Combobox`, not through `inputProps`. `inputProps` and other nested props are exposed as more of an escape-hatch/last-resort and not all properties from these objects are guaranteed to be used or behave as expected.

```tsx
    <Combobox
      items={["Banana", "Orange", "Apple", "Mango"]}
      onChange={(selected) => console.log(selected)}
      onBlur={() => console.log("onBlur")}
      placeholder="Fruit"
      autocompleteProps={{
        // Used for the title in the autocomplete.
        title: "Fruit"
      }}
    />
``` 

`onBlur` isn't directly specified in the component's own props:

https://github.com/segmentio/evergreen/blob/886a4c9b59417aee71d2f5583b0ed5244283c88e/index.d.ts#L1041-L1095

However, because it builds off of another component that has accepts `onBlur`, it _"might"_ work. (Not all components that have `PolymorphicBoxProps` actually use the additional props or spread them on the expected component. In this case, it seems to work as expected.)
