### ISSUE TITLE
CSS Variables for custom stylesheets

### ISSUE THREAD

**Issue by ahsan-sabir** [segmentio/evergreen#1510]
Does evergreen provide css variables for its tokens that can be used in stylesheets like other frameworks such as bootstrap and material?

**Comment by brandongregoryscott** [comment]
We use a css-in-js solution with our UI primitive [`Box`](https://github.com/segmentio/ui-box) as well as [`glamor`](https://github.com/threepointone/glamor). We generally recommend against mixing CSS with Evergreen due to unexpected behavior: https://evergreen.segment.com/foundations/layers#you_don%E2%80%99t_need_classname

A bulk of the styling values can be referenced from our `defaultTheme` object. Check out our [Theming](https://evergreen.segment.com/introduction/theming) documentation for more info!
