### ISSUE TITLE
Is there a way to disable glamor and ui-box?

### ISSUE THREAD

**Issue by alarner** [segmentio/evergreen#1571]
I'm using evergreen in an electron app and I believe that glamor and ui-box are causing content security policy issues due to their inline styles. I don't need to do server side rendering. Is there any way to disabled these libraries?

**Comment by brandongregoryscott** [comment]
I don't think this is possible - the way `ui-box` and `glamor` generate class names and inject styles into the stylesheet is critical to how those styles are applied through component props, whether you're doing client-side or server-side rendering. You wouldn't have a very visually appealing design otherwise!

**Comment by alarner** [comment]
Ok thanks for the info!
