### ISSUE TITLE
Use @reactions/component for storybook and docs examples

### ISSUE THREAD

**Issue by jeroenransijn** [segmentio/evergreen#175]
I want move over the examples and stories to use https://reactions.github.io/component/ for state and component management. This will allow examples to contain all state and data in the example, instead of referring to outside scope.

## Why?

- Allows all the context to be in the examples. No referring to outside scope.
- All examples will use one single convention.
- Easier copy-paste/migration between stories and examples.
- The https://reactions.github.io/component/ package is documented.

## How examples will look

Let's take the `SegmentedControl` component as an example. On the docs page you will see the following snippet of code with all of the state and data visible.

```jsx
<Component
  initialState={{
    options: [
      { label: 'Hourly', value: 'hourly' },
      { label: 'Daily', value: 'daily' },
      { label: 'Monthly', value: 'monthly' },
    ],
    value: 'hourly'
  }}
>
  {({ state, setState }) => (
    <SegmentedControl
      width={240}
      options={state.options}
      value={state.value}
      onChange={value => setState({ value })}
    />
  )}
</Component>
```

## What we are doing now in some cases

As a side note, this component is almost the same to using the Manager that is being used in some components. The reason for moving over to https://reactions.github.io/component/ is a single documented way of doing this (instead of reinventing the wheel).

```jsx
import React from 'react'
import PropTypes from 'prop-types'

export default class Manager extends React.Component {
  static propTypes = {
    children: PropTypes.func,
  }

  constructor(props) {
    super(props)
    this.state = {
      ...props,
    }
  }

  render() {
    return this.props.children({
      setState: (...args) => {
        this.setState(...args)
      },
      state: this.state,
    })
  }
}
```

**Comment by JMFURY** [comment]
@jeroenransijn  So for updating Multi Select example, and for future, I would love your thoughts on the following: 

1. Example (abbreviated for the parts that actually change):
![image](https://user-images.githubusercontent.com/7191639/41755052-01843626-759b-11e8-9513-d47b36517897.png)


I did this with the Stories too and it worked. And you're right, more straightforward to copy/paste in! 

2. Some concerns I had

After you pointed it out and I read through, I knew to add `import Component from "@reactions/component";`  to stories, which might not be obvious unless folks are already familiar with this pattern. Maybe this is just a docs/contrib guide thing.

Also, the nerd in me was sad/concerned with getting rid of `import options from '../docs/starwars-options'` and using this array because it is AWESOME. But really there is value to having a big array like that for some of these components, to show how powerful Evergreen can be with big lists. Just food for thought. 

Anyway, let me know and I can commit these for review.

**Comment by JMFURY** [comment]
@jeroenransijn  deleted my other comment. 

Dug into Gatsby, ran the docs site, and now I understand the scopes & imports. 

Will submit a PR to update multi-select docs, stories, examples now that I have them working.
