### ISSUE TITLE
Idea for Multi-Select Approachability via Deselect or Unselect

### ISSUE THREAD

**Issue by JMFURY** [segmentio/evergreen#196]
Loving the components, and huge fan of Segment in general by the way.. 

I had been trying to figure out how best to leverage `SelectMenu`, and couldn't quite think through how I would manage a Multi-Select (my current use case). 

I installed the library and played around with the Storybook and realized it might possible (& nice) to be able hook into some sort of `onDeSelect()` (or unselect) event handler in order to give more obvious freedom to leverage the existing 'multi' (selected array) support in the component.

I rolled a **very hacky example** which started at top level like this:

![image](https://user-images.githubusercontent.com/7191639/40116061-19a05f6c-58d8-11e8-8691-f515c7f9e79e.png)

Happy to share details, but basically just added `onDeSelect()` as a similar prop/proptype to `onSelect()` further and further in components until I realized the following would probably be necessary to prove it out... 

I hooked in a hack to the  `handleClick()` of `TableRow` based on `isSelected`:

![image](https://user-images.githubusercontent.com/7191639/40117726-5d48d5be-58dd-11e8-9aa6-89c8b0f02d30.png)

Aside from a warning via `div, Box ` ....
![image](https://user-images.githubusercontent.com/7191639/40118246-ff074ae2-58de-11e8-862e-72c46461807b.png) 
(note: maybe I missed a declaration somewhere, or don't yet fully understand composition) 

This did actually work and produce this when clicking a selected item :

![ondeselect-example](https://user-images.githubusercontent.com/7191639/40116026-ff3afcf4-58d7-11e8-9a1c-d233b2c871c2.JPG)

Obviously `console.log` is just to show possibility but I will next start to manage my array of selected values in state/props/Redux, etc. and see what happens.

I could be totally off base, but figured I would drop it in here to discuss with you whether this is an approach you've considered for `SelectMenu` and/or `TableRow`. Again, I may be missing some part how this interplays/impacts other standards or components so definitely not confident this is perfectly helpful, but had to share. 

If there's a better approach I would love to hear about it! Thanks very much!

**Comment by jeroenransijn** [comment]
Hey @JMFURY thanks for showing praise and taking the time to write this issue. We appreciate it a lot!

Select Menu is a continuously evolving component and we get more requirements everyday from our own teams as well. Multi select is not something we ran into just yet, but definitely on our radar.

I haven't tested this use case yet, I thought is should be possible. It seems like there is currently no way to deselect an item is what I understand from your post. It seems like you are on the right track.

If you can it would be awesome to create a PR if you have the time. Otherwise I can take a look at—but I can't promise when or how fast we can move on this atm.

**Comment by JMFURY** [comment]
Thanks for the reply @jeroenransijn and for checking it out! 

I totally hear you. 

Let me know if anything is unclear or if other changes/concepts would be helpful for the broader use cases. Happy to adapt.

For me it is cool just to get involved. So thanks again.

Cheers!
