### ISSUE TITLE
Select Menu Selection + Filtering bug

### ISSUE THREAD

**Issue by jeroenransijn** [segmentio/evergreen#201]
![select menu filtering selection](https://user-images.githubusercontent.com/564463/41482397-5b698b2a-708a-11e8-98b9-1bb184b604c1.gif)

**Comment by jssridhar** [comment]
Hi, first of all nice set of clean components! 

I've run into the same issue for this component and I've fixed this locally. Idea is to move the current keydown event handling to select-menu/src/OptionsList.js instead of select-menu/src/SelectMenuContent.js.  Also, there seems to be an issue with 'Enter' click handler as well, I am not sure if the current behaviour is intended - but i've made changes to it so that if there is a selected option the popover closes with the current selection.

![selectmenu](https://user-images.githubusercontent.com/6094340/42037291-a7fe7f06-7b05-11e8-930d-dc43069ea13b.gif)

Though this fixed the single select issue, there still seems to be an issue in the multi select.

Let me know if the solution makes sense, will be happy to submit a pr!

**Comment by jeroenransijn** [comment]
@jssridhar thanks for showing interest in Evergreen and contributing in this discussion! A PR would be awesome to see what steps you have taken to fix this issue.

The select menu is very much a work in progress. One of our developers actually copied the source code into our app to add some feature to it in which he fixed grouping and selection. @vadimdemedes could you add some context on how you implemented those features together?
