### ISSUE TITLE
[v4] ListItem with `icon` prop support

### ISSUE THREAD

**Issue by mshwery** [segmentio/evergreen#228]
Hey all! I'm thinking it would be pretty sweet to extend the built-in `ListItem` to support `icon`. It's a bit challenging because the parent container (`UnorderedList` or `OrderedList`) might need some knowledge of this to properly setup padding/margin/list-style.

One way to solve this is to _always use icons_ but that's a bit less native, so we may want to avoid that.

Here's a setup I did to get icons instead of the default unordered list bullets: 

```jsx
<UnorderedList listStyle="none" marginLeft={0}>
  <ListItem paddingLeft={0}>
     <Icon icon="tick" marginRight={majorScale(1)} />
     <Text>I Can Has Checkmark Icon</Text>
  </ListItem>
</UnorderedList>
```

It actually might make sense to make the parent responsible for icons since we are technically using a custom `list-style` (which is possible with just css, but these icons might not be compatible with that implementation).

**Comment by jeroenransijn** [comment]
I have been thinking about this for a bit as well. I agree that in our case it might be tricky to do this with just CSS, so I am leaning for the more custom approach. Here are some approached to this I can think of:


## Introduce `UnstyledList`

We could use a `UnstyledList` that is a `UnorderedList` with no styles. We could then add a `icon` + `iconColor` prop to the `ListItem`

```jsx
<UnstyledList>
   <ListItem icon="tick" iconColor="success">...</ListItem>
</UnstyledList>
```

## Introduce `IconList` with `React.Context`

This introduces a new component that can give a icon to an entire list, we can use `React.Context` here to give the icon to the `IconList.Item`.

```jsx
<IconList icon="tick" iconColor="success">
   <IconList.Item>Create new component for this...</IconList.Item>
   <ListItem>...or use ListItem potentially?</ListItem>
</IconList>
```

## Introduce `IconList` with item scoped icons

With this approach you can add an icon to a single item in a list. Can be powerful in some cases. Pote

```jsx
<IconList>
   <IconList.Item icon="tick" iconColor="success">Create new component for this...</IconList.Item>
   <ListItem icon="tick" iconColor="success">...or use ListItem potentially?</ListItem>
</IconList>
```

## Introduce `IconList` with item scoped icons AND `React.Context`

With this approach you can add an icon to a single item in a list. Can be powerful in some cases. Pote

```jsx
<IconList icon="tick" iconColor="success">
   <IconList.Item>Uses props from IconList</IconList.Item>
   <IconList.Item>Uses props from IconList</IconList.Item>
   <IconList.Item icon="warning" iconColor="warning">Override props being passed</IconList.Item>
</IconList>
```

## Thoughts

`Iconlist` might be the wrong nomenclature. I like using `React.Context` here because most use cases will simply require the same icon props in a list. I do think there are use cases in which we want to use different icons within the scope of a list item — having that support build-in might be useful, but maybe out of scope for now.

**Comment by jeroenransijn** [comment]
@mshwery we could totally use `React.cloneElement` here, love this implementation. Do you want to pick this up or should I?

**Comment by mshwery** [comment]
I might not be able to get to it until next week.

Keep in mind we'd still have to tweak `ListItem` to support the `icon` prop and take control of customizing it in lieu of the standard `list-style` value.
