### ISSUE TITLE
[v4] Allow "deselecting" in comboboxes

### ISSUE THREAD

**Issue by Flaque** [segmentio/evergreen#242]
At the moment, a combobox item can be deselected by highlighting the text and deleting it. However, it would be nice if clicking on an item that you've already selected would "deselect" it as a checkmark would normally imply. 

<img width="271" alt="screen shot 2018-07-20 at 2 58 15 pm" src="https://user-images.githubusercontent.com/5942769/43027071-5b06b91e-8c2d-11e8-9226-b8eada91d435.png">

**Comment by JMFURY** [comment]
I took a quick look and I think it should be straightforward since `Combobox` has `Autocomplete` options that derive from `SelectMenu` > `Option` - From there the `onDeselect` method we added for multiselect is available.  

I could take a stab at this.

cc: @jeroenransijn

**Comment by JMFURY** [comment]
@Flaque It turns out I was wrong in a lot of the above assumption (ooops..). This definitely has its differences over Select-Menu. But that's actually good since it is a bit more straightforward. 

@jeroenransijn I have the interaction running after some trial and error. Here are some details:

Within `Autocomplete`'s `renderItem()` we can target the selected item in the same way the 'isSelected' boolean is applied. See comment in the code below:

![image](https://user-images.githubusercontent.com/7191639/43057252-bfbc5618-8e06-11e8-8e62-22203644da87.png)

Changing `onMouseUp` to `onClick` solved an issue where the item would get selected again after clicking it. The deselect and clearSelection (see below) all worked, but the item would get selected again -- all way too fast to see, but seen in the console. 

You may know why the `onMouseUp` was used in the first place so it's probably worth talking it through.

The other key to this was to use the [`Downshift`](https://github.com/paypal/downshift) component's built in clearSelection method / prop. Cool component..

I have some cleaning up to do from trying things before I'd be confident sharing code but I can prep a GIF of the functionality sometime mid-week. 

Seems like you have a ton going on for v4. (stoked) Happy to help whenever this is useful. Cheers!

**Comment by mshwery** [comment]
We may want to expose this as an opt-in: `isClearable` or something.

**Comment by Flaque** [comment]
@JMFURY Feel free to open an "work-in-progress" PR if you'd like!

**Comment by JMFURY** [comment]
All, 

Doing it at the Autocomplete level felt to me like fighting Downshift. Doing the logic within onMouseUp() came with a lot of caveats, fixing one bug caused another and so on..

I am sure with some review/help it could be done more (and cleanly)..

In digging thru Downshift some more I found this: 
https://codesandbox.io/s/0mrl1819qw?from-embed
referred to here by the author: https://blog.kentcdodds.com/introducing-downshift-for-react-b1de3fca0817

I also really liked @mshwery 's idea on `isClearable`, so I'm submitting a WIP PR to show you what I think is pretty clean for an interaction that fights significantly less with Downshift, and matches their interaction a bit more.. Some cleaning up to do, but figured I'd present the idea.

![image](https://user-images.githubusercontent.com/7191639/43162723-9463b9a6-8f51-11e8-9742-97c6c439d4cb.png)

**Comment by samanthakimone** [comment]
Thank u that was good
