### ISSUE TITLE
[v4] Fix SidebarTab icon placement

### ISSUE THREAD

**Issue by jeroenransijn** [segmentio/evergreen#247]
![image](https://user-images.githubusercontent.com/564463/43103828-35a53c96-8e84-11e8-856d-23c9b0320d73.png)

**Comment by jfmaggie** [comment]
@jeroenransijn Do you think it makes sense we just remove the icon? It looks redundant to have this icon since the side bar already have active state to indicate current selected item. With the arrow icon it somehow indicates it is clickable and can be expanded to a dropdown. 

![image](https://user-images.githubusercontent.com/7209644/43103990-bf99af4a-8e84-11e8-92aa-420a4f50342b.png)

^^^ `Sources` selected, `API Access` hovered.

**Comment by jeroenransijn** [comment]
@jfmaggie thanks for bringing this up! I guess we don't need it. We could create an issue out of this to get the input from others, would you want to do that?

**Comment by jfmaggie** [comment]
@jeroenransijn Sure thing :)
