### ISSUE TITLE
Select menu and other components not accessible

### ISSUE THREAD

**Issue by blakeperdue** [segmentio/evergreen#254]
# Issue and steps to reproduce.
Visit the select menu demo: https://evergreen.surge.sh/components/select-menu

Use the keyboard to navigate to the `Select name...` demo button. Press enter to open the menu and notice that it opens and immediately closes. 

This makes the component completely inaccessible for users who primarily use the keyboard (or screenreaders) to navigate. 

* Versions.
v3.2.5

* Screenshots.
![screen recording 2018-07-24 at 01 30 pm](https://user-images.githubusercontent.com/1642071/43155563-bb57b01e-8f45-11e8-81a0-16f3bfd81fd7.gif)

**I would love to know if Segment has a stance on accessibility.**

**Comment by mshwery** [comment]
Hey @blakeperdue ! Thanks for reporting the issue. We've been working on a lot of these interactions to improve accessibility in [v4](https://github.com/segmentio/evergreen/pull/200/)

But this brings up a good point – we should address some issues in v3 as well!

Slightly related: 
https://github.com/segmentio/evergreen/issues/223
https://github.com/segmentio/evergreen/issues/227

Oh, and PRs are always welcome if you are feeling up to it! 😄

**Comment by jeroenransijn** [comment]
@blakeperdue thanks for reporting this! As @mshwery our focus right now is to move to v4 as soon as possible which contains a ton of improvements for interactions patterns and accessibility. We welcome PRs for v3 in the mean time, however, we currently can't make any promises for ongoing v3 support .

I would recommend trying out v4 instead of using v3 and checking out the docs here: [http://evergreen-v4.surge.sh/](http://evergreen-v4.surge.sh/). You can install it with: `yarn add evergreen-ui@next`.

**Comment by blakeperdue** [comment]
Got it, thanks for the recommendation. Will try out v4.
