### ISSUE TITLE
Relatively large footprint on the JS bundle size

### ISSUE THREAD

**Issue by acarl005** [segmentio/evergreen#311]
versions
--------
evergreen-ui: `3.2.4`
webpack: `3.8.1`

My JS bundle size increases quite a bit due to evergreen-ui. **After minify and gzip**, it adds about **60kB** to the bundle including some of the largest dependencies.

evergreen itself: 32kB
ui-box: 10kB
glamor: 7kB
downshift: 5kB
lodash.mapvalues: 4kB

This seems really heavy given there isn't that much added functionality. For comparison, react-dom is a little over 29kB.

**Comment by jeroenransijn** [comment]
Thanks for doing some research on this! I bet `v4` will be even bigger because of `@blueprintjs/icons`. I think it's important to figure out a long term strategy to keep this down (e.g. mono-repo for certain parts). 

That being said, you should consider enabling treeshaking if you are using Webpack. @Rowno might be able to provide more context here.

I appreciate you creating this issue, but I don't see a clear way to resolve this issue at the moment.

**Comment by Rowno** [comment]
Yep, if you upgrade to Webpack 4 you should see a significant drop due to the more advanced tree shaking.

**Comment by epitaphmike** [comment]
I may be missing something, but the only way I was able to get the bundle size own in `v4` was to import the components like this: `import Pane from 'evergreen-ui/esm/layers';`. 

<img width="734" alt="screen shot 2018-11-27 at 2 39 44 pm" src="https://user-images.githubusercontent.com/677832/49106886-5c06f500-f252-11e8-991d-10d82cda4a8d.png">
<img width="567" alt="screen shot 2018-11-27 at 2 40 44 pm" src="https://user-images.githubusercontent.com/677832/49106936-73de7900-f252-11e8-96d9-5f5acc93e1ba.png">


Unfortunately this doesn't do anything about `evergreen-ui/esm/icon/Icon.js`. It still contains all of `@blueprintjs/icons`

I had to edit the Icon.js file and do the same thing to reduce the bundle. 

<img width="788" alt="screen shot 2018-11-27 at 2 36 06 pm" src="https://user-images.githubusercontent.com/677832/49106809-28c46600-f252-11e8-9deb-d8a48ed9fe44.png">
<img width="747" alt="screen shot 2018-11-27 at 2 35 54 pm" src="https://user-images.githubusercontent.com/677832/49106810-28c46600-f252-11e8-9fb5-8c9f9f34913a.png">

Am I missing some config in webpack @Rowno ?

**Comment by Rowno** [comment]
I don't think the VS Code Import Cost plugin does tree shaking, it just traces all the files imported from the file you imported. To see the real tree shaken size you should use the [webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer).

As for the icons size issue, I'm currently working on tree shaking support for the icons. In Evergreen v5 you'll import individual icons directly instead of referencing them via a string, which will allow Webpack remove almost all of the icons (since less than 5% of them are used internally).

For example, this:
```jsx
import { Icon } from 'evergreen-ui'
<Icon icon="cross" />
```
Will become this:
```jsx
import { CrossIcon } from 'evergreen-ui'
<CrossIcon />
```
