### ISSUE TITLE
"View on GitHub" links in components documentation are all broken

### ISSUE THREAD

**Issue by justin0022** [segmentio/evergreen#327]
For instance, https://github.com/segmentio/evergreen/tree/master/src/Alert in https://evergreen.surge.sh/components/alert

**Comment by shui91** [comment]
Hi, I thought I'd take a shot at this issue, as a chance to get involved with OSS during this year's Hacktoberfest!

The issue raised by @justin0022 here is an active bug on the live version of the docs ([Alert docs](https://evergreen.surge.sh/components/alert)). As you can see in my screen shot below, the url on the `View in Github` link uses the capitalized name of the component. 

<img width="1438" alt="screen shot 2018-10-07 at 1 37 25 pm" src="https://user-images.githubusercontent.com/11592023/46586741-9b297e80-ca37-11e8-9ba9-5f91cd2a8b84.png">

But when trying to reproduce locally, I realized that this issue has been fixed in [#310](https://github.com/segmentio/evergreen/pull/310) by using the `kebabCase` method when rendering the link in the `ComponentReadme` component. 

So I think that perhaps the website hasn't been re-deployed after the fix was merged. Could one of the code owners/maintainer's (@jeroenransijn) confirm this?

**Comment by jeroenransijn** [comment]
Thanks for pointing this out! This has been fixed in the new v4 docs: https://evergreen.segment.com/
