### ISSUE TITLE
Change placeholder in SelectMenu search input

### ISSUE THREAD

**Issue by lndgalante** [segmentio/evergreen#431]
Is there a way or prop to modify the placeholder from the search input?

<img width="229" alt="captura de pantalla 2018-11-05 a la s 21 41 57" src="https://user-images.githubusercontent.com/2475912/48035640-af01f680-e143-11e8-84c2-526c37283466.png">

**Comment by mshwery** [comment]
I don't think there's a prop exposing that right now, but that's a great idea. I think we may want to allow consumers to modify any props via something like a `filterProps` prop. What do you think? Wanna take a stab at a PR @lndgalante ?

**Comment by jeroenransijn** [comment]
@mshwery yeah `filterProps` would be inline with what we do elsewhere.

**Comment by lndgalante** [comment]
Sure I will give it a try! @mshwery

**Comment by vadimdemedes** [comment]
I think we shouldn't expose `filterProps` and allow overriding any props here. That strategy will lead to a state where we will have no idea if our changes break someone else's UI, since they can override anything. Minor release can become a breaking release for some users.

Since this is a valid feature request and exposing `filterProps`, in my opinion, is too much for such a simple change, I would expose `filterPlaceholder` prop instead.

**Comment by lndgalante** [comment]
Great I also believe a `filterPlaceholder` it's a better option in this case.

**Comment by mshwery** [comment]
This is implemented!
