### ISSUE TITLE
Add List component

### ISSUE THREAD

**Issue by J-F-Liu** [segmentio/evergreen#437]
Suggest change `<UnorderedList />` to `<List />`, and `<OrderedList />` to `<List ordered />`.

**Comment by vadimdemedes** [comment]
@J-F-Liu What benefits would this change have?

**Comment by J-F-Liu** [comment]
Easier to read and write, and to toggle a list is ordered or unordered.

**Comment by vadimdemedes** [comment]
> Easier to read and write

I don't see how is it easier to read and write, it's just two different names. I would actually argue that `<List>` is worse, because without looking at documentation, how do you know if this `<List>` is ordered or unordered?

> toggle a list is ordered or unordered.

That sounds like a unique case, to be honest. When would you need to change the type of the same list between ordered and unordered?

**Comment by J-F-Liu** [comment]
List is a higher level of abstraction, we usually don't care so much about whether it is ordered or unordered, so List is fine and can distinguished by look at the ordered prop. The only concern is breaking change which can be avoided by still keep UnorderedList and OrderedList.

This is only my personal opinion, you are free to close this issue or accept it.

**Comment by vadimdemedes** [comment]
Sorry, I don't think there are enough benefits to make this breaking change.

**Comment by mshwery** [comment]
@J-F-Liu for the time being you could easily add a wrapping component that achieves what you want:

```js
import { UnorderedList, OrderedList } from 'evergreen-ui'

export default function List({ ordered, ...props }) {
  return ordered
    ? <OrderedList {...props} />
    : <UnorderedList {...props} />
}
```
