### ISSUE TITLE
Combobox throws warning for <Table.Row> onClick / onSelect

### ISSUE THREAD

**Issue by karltaylor** [segmentio/evergreen#451]
Receiving this warning when I added a `Combobox`.

```js
<Combobox
  items={['Apples']}
  onChange={selected => console.log(selected)}
  placeholder="Fruit"
  autocompleteProps={{
    title: 'Fruit'
  }}
/>
```
`Warning: <Table.Row> expects 'onSelect' prop, but you passed 'onClick'.`

Using: `"evergreen-ui": "^4.7.1"`

**Comment by mshwery** [comment]
Hm, yeah – this happens because `Combobox` is using `Table.Row` under the hood. I think we may need to remove that warning since it doesn't necessarily make sense for all consumers (especially internal consumers).

@vadimdemedes what do you think? I don't have the full context of why that warning was added.

**Comment by mehmetnyarar** [comment]
I've encountered this issue while implementing `Autocomplete` with `TagInput`.

**Comment by sergii-zhuravel** [comment]
The same warning, Using: "evergreen-ui": "^4.7.1"

**Comment by sergii-zhuravel** [comment]
The same issue with version '4.15.0'
`warning.js?e2a0:4 Warning: <Table.Row> expects `onSelect` prop, but you passed `onClick`.`
