### ISSUE TITLE
Popover does not bring focus back to target

### ISSUE THREAD

**Issue by 7c78** [segmentio/evergreen#452]
1. Go to [https://evergreen.segment.com/components/popover](https://evergreen.segment.com/components/popover)
1. Trigger a popover by clicking a button
1. Click at background to close popover

Expect: Focus is brought back to button.
Actual: Focus is not brought back to button.

P/S: I clone the lastest code and it works as expected, but the popover in above page doesn't.  I am curious which is better behavior?

**Comment by mshwery** [comment]
Interesting find. I noticed that using the escape key to close the menu _does_ properly bring focus back to the button.

**Comment by cliffpyles** [comment]
If no one is working on this, I can take a shot at it.

**Comment by cliffpyles** [comment]
From what I can tell this is related to a conflict with Gatsby's router (@reach/router) and the Popover component. The router manages focus programmatically, and changes `document.activeElement` to a div (`id="gatsby-focus-wrapper"`). The Popover component is expecting `document.activeElement` to be equal to `document.body`. Because of this the focus doesn't get triggered on the target. https://github.com/segmentio/evergreen/blob/master/src/popover/src/Popover.js#L191


I'll still need to verify this, but think this bug will occur anytime the Popover is used with Gatsby 
 or @reach/router.

**Comment by mshwery** [comment]
Seems like we may want to use a more generic handler for bringing focus back. Could potentially use something like a focus trap hook? I think in that case it'd be more generic and could be used in multiple places.

**Comment by cliffpyles** [comment]
That seems like a clean approach to me. If we want to use hooks, we would need to convert the component to a functional component though. Would that be in scope of this issue or should another be created?

**Comment by mshwery** [comment]
Seems like this issue is no longer present. Closing.
