### ISSUE TITLE
Link should not change font-size

### ISSUE THREAD

**Issue by ericclemmons** [segmentio/evergreen#454]
As shown below, the `<Link>` element changes the `font-size` of the text, even though it's within a `<Heading>` element.

> **"But @ericclemmons, you can just use an `a` tag!"**
> -- Knee-jerk Reaction, PhD

When using a project like `mdx-js`, consistent theming relies on all `a` tags using `Link` instead, which makes this not a valid option.

> <img width="826" alt="screen shot 2018-11-19 at 1 21 30 pm" src="https://user-images.githubusercontent.com/15182/48735785-26349180-ebfe-11e8-812f-55c4a6f859c8.png">
See: https://codesandbox.io/s/32xnk54ov1

**Comment by mshwery** [comment]
Evergreen doesn't currently support _cascading props_ like this. I think it would be an interesting addition, but it would also conflict with the way style props are bound.

Typically, in an example like yours, you'd have to specify the link `size` prop to match your heading's `size`.

**Comment by emadabdulrahim** [comment]
@mshwery Wouldn't it be possible to set the default *Link* `fontSize="1em"` which would act the same way as `currentColor` property you guys follow in the `Icon` component?

Thoughts?

**Comment by mshwery** [comment]
The thing you probably want to try here is `fontSize="inherit"` on the link component. We try to avoid inheritance/cascading styles as a rule. If just moving your component around the tree suddenly causes it to look differently that's a problem.

Since this is a much larger philosophical change that goes against the grain of how Evergreen strives for style encapsulation I am going to close the issue for now.
