### ISSUE TITLE
onSubmit or onEnter prop for SearchInput

### ISSUE THREAD

**Issue by danedavid** [segmentio/evergreen#507]
Since `SearchInput` will only be used as a search text field, maybe we can support an `onSubmit` or `onEnter` prop that gets triggered when Enter key is pressed. That way user can get rid of the keyPress handler logic everytime.

**Comment by mshwery** [comment]
You should probably be using `onChange` or `onInput` instead of keypress, unless you have a good reason to use that.

Changing `SearchInput` to behave like a form submission on its own is outside the scope of its responsibilities as a component. You can pretty easily handle that yourself, too:

```jsx
<form onSubmit={handleSubmit}>
  <SearchInput />
</form>
```

Doing something similar to this will trigger the native behavior, which is to submit a form when pressing the enter key on a text input.
