### ISSUE TITLE
SelectMenu - React does not recognize the "closeOnSelect"

### ISSUE THREAD

**Issue by ald890** [segmentio/evergreen#605]
```    
"evergreen-ui": "^4.18.1",
"react": "^16.8.6",
"react-dom": "^16.8.6",
```

I have Next.js app and paste first example from [docs ](https://evergreen.segment.com/components/select-menu/) "Single selected item" 

My import:
```
import { Button, SelectMenu } from 'evergreen-ui'
import Component from '@reactions/component'
...
<Component initialState={{ selected: null }}>
            {({ setState, state }) => (
              <SelectMenu
                title="Select name"
                options={
                  ['Apple', 'Apricot', 'Banana', 'Cherry', 'Cucumber']
                    .map(label => ({ label, value: label }))
                }
                selected={state.selected}
                onSelect={item => setState({ selected: item.value })}
              >
                <Button>{state.selected || 'Select name...'}</Button>
              </SelectMenu>
            )}
          </Component>
```

And then I have an error:

```
Warning: React does not recognize the `closeOnSelect` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `closeonselect` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
in div (created by Box)
```

**Comment by calumbrodie** [comment]
I think that:
`closeOnSelect` needs to be destructured out of the props here:

https://github.com/segmentio/evergreen/blob/master/src/select-menu/src/OptionsList.js#L227

I'll make a PR but I can't test it currently as I'm not sure how to link evergreen locally in order to verify fixes. Seems it relies on building a commonjs package, but I'm not clear on the workflow of how to link a development version of evergreen to my project.

**Comment by solon-aguiar** [comment]
@calumbrodie I think that your solution is right.

Did you take a look at the [Contributing section](https://github.com/segmentio/evergreen#contributing-to-evergreen) of the readme? If you run the storybook you can test it.
