### ISSUE TITLE
Error: Uncaught [TypeError: Cannot read property 'querySelector' of null]

### ISSUE THREAD

**Issue by eloiqs** [segmentio/evergreen#684]
I am getting the above error in `OptionsList.js:96:22` when trying to control the `<SelectMenu />` component in jest with react-testing-library.

Unfortunately I could not reproduce in isolation in codesandbox, so something is telling me this might arise because of some side effect caused in my app by the selection of an item.

In my tests I simply open the SelectMenu with a click, type something in the filter input, and click one of the options. I was expecting that it would effectively trigger all the necessary updates to put my app in some state, but it threw the above error instead.

It just seems to be a problem when rendering in jest-dom, I can't reproduce manually in a real browser 😞

I don't know if simply checking if `this.searchRef` is defined in the `requestAnimationFrame` callback before focusing the input could be considered? But then, why would it be undefined after a click?

Let me know if I can provide more context, I can also share my app through code sandbox.

**Comment by mshwery** [comment]
It's probably because the component is unmounting so quickly that by the time `requestAnimationFrame` fires it's already unmounted.

I think your intuition is correct – we could check for the ref before using it.

The more correct way to handle this would be to keep a reference to the requestId (from` requestAnimationFrame`) and pass it to `cancelAnimationFrame` on `componentWillUnmount`
