### ISSUE TITLE
v5 Roadmap

### ISSUE THREAD

**Issue by Chrischuck** [segmentio/evergreen#735]
Curious to see what we can do to get the ball rolling on v5.

An [issue](https://github.com/segmentio/evergreen/issues/379) was made for it a while back and 1/2 committed changes were made so far.

What I'd personally like to see in v5:
* Robust theming
* Hooks
* Tree shaking support w/ icons

@mshwery brought up [here](https://github.com/segmentio/evergreen/pull/723) the two different ways we could roll out a v5:
> 1. Strict mode: We could target these PRs to a v5 branch (probably need to start fresh since the current one is quite stale) and once we convert everything over... then we finally release v5 to npm
> 2. Incremental mode: Ship these PRs as v5 release candidates so we can start opting into them without broadly releasing v5. This will allow us to continue to make breaking changes on v5 until we've finished all the incremental PRs. (Though maybe we still want to target a new v5 branch for that instead of master?)

**Comment by mshwery** [comment]
We've also started a v5+ vision/roadmap internally between some ui engineers and our design team. We'll start sharing more broadly here as major areas of investment start to bubble up – would love to get the feedback from this open source community on what we are thinking of (hint: you already named 3 themes on roadmap 😉)

We'll have more to share here in the next few weeks.

**Comment by mshwery** [comment]
As for the existing v5 branch, we can evaluate if those changes still make sense (but will probably have to reapply them because much has changed since then.

**Comment by xAvarice** [comment]
I think customisation or at least documentation regarding customisation should be a critical priority or you are going to lose developer adoption that you could have otherwise (at/re)tained.

**Comment by Chrischuck** [comment]
@xAvarice could you explain what you mean by customization? Is it better theming support?

**Comment by Chrischuck** [comment]
@mshwery has there been any preexisting work done for tree shaking support w/ icons?

**Comment by xAvarice** [comment]
> @xAvarice could you explain what you mean by customization? Is it better theming support?

It's hard to say without theme documentation, can I be pointed to the location I've seen referred to of an early branch that documented theme properties?

When I say customisation, I mean that many people will be using SCSS / LESS / CSS alongside evergreen and should be able to override (especially when it comes to nesting, hover, responsive, etc) 

If you take a look at this issue, and I will provide the only working method I have found after it:
https://github.com/segmentio/evergreen/issues/737

![Screenshot 2020-02-07 at 13 17 24](https://user-images.githubusercontent.com/17517508/74032622-4d66b280-49ac-11ea-94e7-cb5bde4854b2.png)

There is an inconsistency in that with other components allow whatever it is that I am doing from Babel (next-sass?) parsing SCSS (CSS modules) into JS which I can then pass to some components but not others... If my setup is complicated then it was not by choice, it was the only working method and I think many people going for SSR are going to run straight into that problem. I hit it within the first few hours of using Evergreen. (Updating that issue more atm)

Customisation versus theming to me would be CSS overriding. Whereas your theming is passing javascript properties.

I had a conversation with Jakob where I have solved the issue of going SASS / CSS module to javascript properties in quite a novel way I hadn't considered before so that takes a lot out of it... but I ran into an inconsistent (I believe?) with popover which there's little anyone can do anything about. I am hoping it is an issue with the glamor class assignment so it can be easily resolved.

![Screenshot 2020-02-07 at 13 23 28](https://user-images.githubusercontent.com/17517508/74033093-560bb880-49ad-11ea-8a03-568b6d9d7751.png)

**Comment by Chrischuck** [comment]
@xAvarice I see your points and I'm a big fan of CSS modules myself.

I'm curious if your issues occur outside of SSR as well and it's more of a fundamental issue of the library over just being SSR. Either way hopefully I can get some time to spin something up and test it a little. Hopefully @mshwery knows more about this stuff

With regards to the theme properties, unfortunately I scrapped that since there were just so many and it felt wrong having an incomplete list. [here](https://github.com/segmentio/evergreen/tree/master/src/theme/src/default-theme) is the link to the src code for all of the theme stuff

**Comment by Jakobo** [comment]
Having lived in evergreen's theming directory a _tad_ too long, I do have some v5 thoughts around theme specifically.

**Long Live ui-box?** `ui-box` is critical to v4 of evergreen. It also informs several other design decisions made in the framework; it's why we use glamor, it's why we prefer css as properties, and it's why we don't have `styled-components` or `emotion` loaded by default. But I think with v5 breaking backwards compatibility, there's a chance to reduce the number of things we maintain by deploying something like `styled-system` & an alternate css-in-js solution. The advantage to this route is that the theme / theme overrides / theme provider stories are already solved and don't require any innovation time. The downside is that in a `styled-system` world, ui-box can be reduced to something like:

```js
import styled from "@emotion/styled";
import PropTypes from "prop-types";
import { space, layout, flexbox, background, border, position, shadow, textAlign } from "styled-system";

const Box = (all) => <Box.Styled {...all} />;
Box.Styled = styled.div`
  ${space}
  ${layout}
  ${flexbox}
  ${background}
  ${border}
  ${position}
  ${shadow}
  ${textAlign}
`;
Box.propTypes = {
  ...space.propTypes,
  ...layout.propTypes,
  ...flexbox.propTypes,
  ...background.propTypes,
  ...border.propTypes,
  ...position.propTypes,
  ...shadow.propTypes,
  ...textAlign.propTypes,
};

export default Box;
```

**Theme is an Object** This is something I feel evergreen-ui already does well. For example, the `defaultTheme` has easy to follow properties and can be extended and modified. In v5, I'd probably remove many of the `get____` methods just to reduce the exposed surface area and prioritize primitives. However, _highly specific accessors_ such as a `getIcon(name)` can not only make theming some of the more challenging aspects of evergreen easy, it also decouples evergreen from an icon system.

For end users, selecting to include the evergreen icons becomes a matter of which default theme you build upon: `import {defaultTheme} from "evergreen-ui"` for the evergreen icons or `import {defaultTheme} from "evergreen-ui/core"` for an empty `getIcon()` method you'll need to implement yourself.

**Hooks** `useTheme` should get us 99% of the way there. Are there other hooks in particular we really want such as `useIntentColor` or `useNeutralScale`?

---

Regarding the release mode, **Option 2** feels much better. We should always be shipping RCs to npm in order to put workable code in people's hands. It'll also make it easier to collect all of the breaking changes as we go instead of trying to gather them towards the end of the v5 development.

**Comment by mshwery** [comment]
Closing as v5 has shipped, but keeping these remaining comments in consideration for v6 and beyond! Thanks all.
