### ISSUE TITLE
Bug: Cannot map elements dynamically into Menu

### ISSUE THREAD

**Issue by xAvarice** [segmentio/evergreen#740]
- Issue and steps to reproduce.
Try to .map an array into Menu, errors out with no items in menu (Error in Menu src)

https://github.com/segmentio/evergreen/blob/37d141457a82297fc2de14b252c68fa1a5e965f1/src/menu/src/Menu.js#L36

**Comment by Chrischuck** [comment]
Seems like a decent first issue. Do you have a PR ready to go for it/working on it?

**Comment by sdoan16** [comment]
I'll work on this

**Comment by xAvarice** [comment]
> Seems like a decent first issue. Do you have a PR ready to go for it/working on it?

Not a good first issue for me, still learning the source code and intentions behind some of the approaches chosen. Getting a clearer and clearer idea each day. I will be depending on evergreen heavily for 3 projects so I will give back. :) 

@sdoan16 if there is a chat channel etc I would be interested in your work on this.

**Comment by Chrischuck** [comment]
@xAvarice 

Dug into it for some exploratory work. Are you using the `Menu.Item` component inside the menu?

<img width="575" alt="Screen Shot 2020-02-08 at 9 19 32 PM" src="https://user-images.githubusercontent.com/13311268/74096842-d10dc580-4ab8-11ea-8fac-b617665aa672.png">
<img width="331" alt="Screen Shot 2020-02-08 at 9 19 19 PM" src="https://user-images.githubusercontent.com/13311268/74096843-d23ef280-4ab8-11ea-955b-af285b24bebb.png">

The above works, if I switch out `Menu.Item` for `li` I end up with your error.

**Comment by mshwery** [comment]
This is perhaps an area where the DX can be improved. We probably shouldn't throw in production environments, but this is an indication that Menu is not being used properly.

https://github.com/segmentio/evergreen/blob/37d141457a82297fc2de14b252c68fa1a5e965f1/src/menu/src/Menu.js#L31-L37

Instead of throwing in production, we should throw/warn in development mode that Menu requires `Menu.Item` somewhere in its child tree. 

If you want to use custom menu items, refer to the example from the docs: https://github.com/segmentio/evergreen/blob/78cf402525b59fcac49e53236f382dba0c60256f/docs/src/pages/components/menu.mdx#custom-menu-items

>The `Menu` by itself offers focus management to elements inside of the component that either have `[role="menuitemradio"]` or `[role="menuitem"]`.

**Comment by mshwery** [comment]
Let me know if that solves your use-case (check out the custom example from the docs and/or @Chrischuck's example). If you find there is a bug or still an issue, feel free to comment on the thread and we can reopen the issue.
