### ISSUE TITLE
[Question] Typescript Omit and React.ComponentPropsWithoutRef

### ISSUE THREAD

**Issue by leesiongchan** [segmentio/evergreen#834]
Sorry I am not sure if this is the right place to ask, but I am trying to use `Omit` to create my own props but it doesn't seem to be working for those props are extending to `React.ComponentPropsWithoutRef<T>`.

For example,
```typescript
type CountryComboboxProps = Omit<
  ComboboxProps,
  "items" | "itemToString"
>;
```

You will not see any typing if you try to use the `CountryComboboxProps` above.

**Comment by mshwery** [comment]
You are right. It seems that we cannot use `React.ComponentProps<T>` to infer props from ui-box's `Box` component because it relies on a custom type signature that doesn't map 100% to React's (that's the only way to get some support for generic type inference in a component).

We should be able to swap that out with something a bit more accurate in Evergreen.

**Comment by mshwery** [comment]
Types are much better in v5 and you should generally be able to use `Omit` or `React.ComponentProps<T>`.

Additionally, in some advanced cases you may need to use ui-box's `PolymorphicBoxComponent<Element, Props>` to extend polymorphism to your own custom components.

Closing for now since this has been mostly remedied in v5+
