### ISSUE TITLE
<MenuItem> prop secondaryText should be called rightView

### ISSUE THREAD

**Issue by cstrat** [segmentio/evergreen#840]
This would make it the same as the `<TableCell>` component because it takes a node and not strictly text. Standardising the language helps with expected behaviour.

It would be a breaking change to implement it alone in v4 so perhaps the element could simply accept both. v5 could remove the old `secondaryText` prop?

Thoughts?

**Comment by mshwery** [comment]
Agree on more consistent naming for this pattern of passing in `React.ReactNode`s – probably more aptly named `*Component`, e.g. `leftComponent` `rightComponent` or whatever descriptor makes sense for how it's positioned/rendered.

**Comment by akleiner2** [comment]
Closing out due to inactivity. I think we could probably add this in a backwards-compatible way i.e. if `secondaryText` was a string, keep current behavior, otherwise render it as-is. 

Tend to avoid directional prop names like `left*`, `right*`, as they're too tightly coupled to the design. If the design changes, the prop names must change too. Not to mention things like RTL!
